### ISSUE TITLE
🐞[bug]: Train Animation Direction Bug: Should Move Left to Right Instead of Right to Left

### ISSUE THREAD

**Issue by GauravDeshmukh0909** [Anjaliavv51/Retro#578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

# Train Animation Direction Bug

### **Bug Description**
The train animation is currently moving from **right to left**, but the expected behavior is for it to move from **left to right**. This issue affects the CSS animation that is applied to the train graphic on the page.

---

### **Steps to Reproduce**
1. Navigate to the **About Us** page of the website.
2. Scroll down to the footer section where the train animation is displayed.
3. Observe that the animation moves from **right to left**, which is the incorrect direction.

---

### **Proposed Solution**
Modify the `@keyframes` animation so that the train starts from the left side of the screen and moves to the right. Here’s the updated CSS:

```css
@keyframes moveTrain {
    0% {
        left: -100%; /* Start off-screen to the left */
    }
    100% {
        left: 100%; /* Move off-screen to the right */
    }
}
```

### **Expected Behavior**
The train should move from the **left side of the screen** and travel to the **right**. This is the expected movement for the animation.

---

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f8ee638a-108e-4937-8a88-cf7024b6885a)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository
